### ISSUE TITLE
Error in doc.lua

### ISSUE THREAD

**Issue by hellbe** [stevedonovan/LDoc#182]
Hi!

Got an error when parsing our project files with LDoc, from the file doc.lua. Within the function Item:build_return_groups() there is a call to quote() which is nil. Suggested fix (that solved it for me) is to add [local quote = tools.quote] before line 916. Like it is done in the other functions in the file.

regards

Simon

**Comment by stevedonovan** [comment]
Has been fixed in Master for a while, so I'm closing. Thanks.
