### ISSUE TITLE
@usage rendering retains leading white-space from source comment

### ISSUE THREAD

**Issue by E14** [stevedonovan/LDoc#191]
In a comment with `@usage`, all white-space from right after the double-dash is added to the rendered source code in documentation. This prevents clean copy&paste and also prevents developers from writing nice comments.
## Example

``` lua

---
-- @usage
--     foo = bar(flag, ...)
```

turns into

``` lua
     foo = bar(flag, ...)
```

instead of

``` lua
foo = bar(flag, ...)
```

When trying to remove all white-space from the start of the code in the comment, comments in the `@usage` sample code break the `@usage` context:

``` lua

---
-- @usage
--foo = bar(flag, ...)
---- The next line is essential
--bar=bar-foo
```

**Comment by stevedonovan** [comment]
Sorry about the delay - been MIA!  The fix is to strip any leading spaces in usage blocks, based on the indentation of the first line.

**Comment by E14** [comment]
> Sorry about the delay - been MIA!
It happens... *cough* (Okay, I blame GitHub notifications failing for mine.)

Anyway, my incredible test file renders great in LDoc 1.4.6, in case you were leaving this open due to missing confirmation :)
