### ISSUE TITLE
LDoc not reading config.id under at all

### ISSUE THREAD

**Issue by deepakjois** [stevedonovan/LDoc#219]
I am using LDoc  with Lua 5.2 on OS X El Capitan. I have tried using both the version from Luarocks, and from Github, and I am experiencing the same issue.

I am trying to setup API docs w/ LDoc for https://github.com/deepakjois/luaharfbuzz

I have a very simple config at the root:
```
file = 'src'
examples = 'examples'
```

When I run LDoc (by just doing `ldoc`), I get this error:

```
ldoc: missing required parameter: file
```

But like you see above, the `file` key is right there in the config.ld file.

Am I doing something wrong? I tried different things, and I was able to make LDoc generate docs for me by specifying arguments on the commandline. But reading `config.ld` just isn’t working for me. So I cannot do things like specify examples etc.

Thank you for any pointers as to how I could debug the problem.

**Comment by afarran** [comment]
Are you pointing to the *config.ld* file in the command-line arguments?
Here's an example (notice the dot at the end):
`C:\> lua.exe .\ldoc\ldoc.lua ..\Source\doc\config.ld .`

**Comment by deepakjois** [comment]
The `ldoc -h` output says that if you don’t specify anything, ldoc looks for `config.ld`  in the current folder. I expected that to work. Anyway, I have tried both options

```
ldoc
```

and

```
ldoc -c ./config.ld
```

**Comment by afarran** [comment]
I think you're missing the dot at the end of the line - see my example above.

**Comment by deathbeam** [comment]
try ldoc .

**Comment by deepakjois** [comment]
Thank you. Looks like I did not read the help output correctly. Sorry to bother.
