### ISSUE TITLE
How to run tests?

### ISSUE THREAD

**Issue by mpeterv** [stevedonovan/LDoc#226]
Running `make test` gives

```
cd tests &&  ldoc . && diff -r docs cdocs && echo ok
reading configuration from config.ld
file or directory does not exist: 'one 1.md'
make: *** [test-basic] Error 255
```

**Comment by stevedonovan** [comment]
Sorry about that! I've now added `run-tests.lua` and now everything seems to work fine. The first step is to generate the 'correct' layout:

    lua run-tests.lua update

and thereafter just 'lua run-tests.lua'.  Several changes were needed to make this reproducible:

  *  documents are always written with Unix line-endings
  *  `--testing` flag sets version and date to constants
  *  there was a nasty little bug with Markdown document sections with Windows line endings

In time we can add more elaborate tests, but the framework seems to be sound now.

**Comment by mpeterv** [comment]
Thanks!
