### ISSUE TITLE
CSS: ordered lists don't display properly

### ISSUE THREAD

**Issue by n1tehawk** [stevedonovan/LDoc#227]
I've been trying to use an ordered (= numbered) list in LDoc (plus markdown) based documentation and found it was rendered "disc" style, despite looking normal in HTML:
```html
<ol>
<li>one</li>
<li>two</li>
</ol>
```

I think the culprit is the CSS definition in https://github.com/stevedonovan/LDoc/blob/aa4cd9daf8fbed4b122b025fbc82e5ca53d97416/ldoc/html/_reset_css.lua#L32, where `list-style: disc;` is associated with every `<li>`, regardless of whether it's "ordered" or "unordered". With that line commented out, ordered lists work as expected (i.e. use `list-style-type: decimal`).

Regards, NiteHawk

**Comment by stevedonovan** [comment]
Cool, for now I've just disabled that explicit list style, since the default is sensible.

**Comment by n1tehawk** [comment]
Hi Steve, and Thanks!

It should be safe to remove that line, as the <i>ldoc/html/ldoc_*css.lua</i> files define an explicit `list-style-type: disc` for `ul` elements anyway.
