### ISSUE TITLE
How to configure to support Dependencies

### ISSUE THREAD

**Issue by dpull** [stevedonovan/LDoc#232]
like this:

https://github.com/stevedonovan/Penlight/blob/master/lua/pl/List.lua

	--
	-- Dependencies: `pl.utils`, `pl.tablex`
	-- @classmod pl.List
	-- @pragma nostrip

**Comment by stevedonovan** [comment]
This isn't a 'structured' LDoc feature; it just puts the module names in backticks, which is a short form of "@{ref}".  So this works because LDoc knows these symbols and expands to a reference link.
