### ISSUE TITLE
Blank lines inserted after end-of-block comments

### ISSUE THREAD

**Issue by Alloyed** [stevedonovan/LDoc#240]
The region the syntax highlighter matches for comments normally includes a newline, so the output html ends up looking like

```
<span> -- my comment
</span> local code = ...
```

note that the newline is _inside_ the span tags.
This is a little wierd, but harmless, unless you end a code block with a comment. Even though the lexer should be matching against the end of string as opposed to a newline, a newline seems to get added anyways:

```
<pre>
<span> -- my comment
</span>
</pre>
```

which gets rendered as an ugly chin in code blocks:
![2016-06-17-230215_719x271_scrot](https://cloud.githubusercontent.com/assets/137977/16168711/9ab2c0a0-34df-11e6-84ac-b183fb2cfaa5.png)

**Comment by stevedonovan** [comment]
Good analysis! Explicitly checked last comment token in prettifier, much better. Also found us a nice juicy bug when a fenced code block was last in a document or section.

**Comment by Alloyed** [comment]
resolved, ty
