### ISSUE TITLE
Add an option to specify lua binary path/name

### ISSUE THREAD

**Issue by rbgarga** [stevedonovan/LDoc#260]
I was trying to upgrade awesome to 4.0 on FreeBSD ports tree and noted there are multiple references to lua binary as simply 'lua', without any path, and all hardcoded.

On FreeBSD you can have multiple lua versions installed and then binaries are /usr/local/bin/lua52, /usr/local/bin/lua53, ....

It would be nice to have a way to define lua binary path and name during build otherwise it's impossible to build it on FreeBSD

**Comment by stevedonovan** [comment]
Very good idea! Linux also uses actual executables like lua5.2 etc, but there's a managed symlink. And it will be useful for Windows people as well.

**Comment by rbgarga** [comment]
It was supposed to be an issue on awesomewm/awesome, bad repo, sorry
