### ISSUE TITLE
Crash on start: attempt to concatenate a nil value (local 'vtype')

### ISSUE THREAD

**Issue by bew** [stevedonovan/LDoc#267]
In a terminal, when running `ldoc` it crashes immediately:
```
$ ldoc
lua: /usr/share/lua/5.3/pl/lapp.lua:317: attempt to concatenate a nil value (local 'vtype')
stack traceback:
	/usr/share/lua/5.3/pl/lapp.lua:317: in function 'pl.lapp.process_options_string'
	(...tail calls...)
	/usr/bin/ldoc:79: in main chunk
	[C]: in ?
```
I tried to reinstall, without success.
I'm on archlinux, `uname -r` => `4.10.8-1-ARCH`
The package version is: `1.4.6-1`

thanks

**Comment by stevedonovan** [comment]
Sorry about that - there was a Penlight version with a bug that broke ldoc. Reinstall Penlight with luarocks or from the zip (1.5.2) and the error should go away.

**Comment by bew** [comment]
Reinstalled penlight, and it works perfectly, thanks!
