### ISSUE TITLE
Automatic alphabetic sorting

### ISSUE THREAD

**Issue by ghost** [stevedonovan/LDoc#42]
When splitting modules into multiple files, it is impossible to get an overall alphabetically sorted function list in the merged documentation for that module, unless I split up the functions to the multiple files by alphabetical needs instead of senseful categories (which I wouldn't want to do obviously). By sorting in-file, I can only get partial list sections sorted but not the module as a whole.

Therefore, alphabetic sorting support in LDoc should be added.

It would be good if it was possible to make exceptions, e.g. I would always want the "new" and "delete" functions of my class types first, then all the other functions alphabetically sorted.

One universal and very flexible way of specifying this would be to specify a sort function in the config.ld which takes two function names (or other sort of member's names) and returns true if the first comes before the second, and false if the second comes before the first:

``` Lua
sortfunc.mymodule.mytype = function(first, second)
    -- exceptions:
    if first == "new" then
        return true
    elseif first == "delete" then
        if second == "new" then
            return false
        end
        return true
    elseif second == "new" then
        return false
    elseif second == "delete" then
        return false
    end
    -- regular sorting:
    if table.sort({first, second})[1] == first then
        return true
    else
        return false
    end
end
```

**Comment by alerque** [comment]
As far as I can see modules are currently sorted alphabetically by default. If there is something I'm missing here feel free to comment but this must have gotten implemented already.
