### ISSUE TITLE
Identical ad hoc sections in multiple files result in duplication

### ISSUE THREAD

**Issue by nilnor** [stevedonovan/LDoc#8]
I'm using (abusing?) ad hoc sections for documenting class instance variables, like so:

``` lua
--- Instance fields. These can be set only for an buffer instance, and not
-- globally for the module.
-- @section instance

--- foo is bar,  blah blah
foo = nil

--- @section end
```

This worked fine for the first file, but when doing the same for a second file in the module this results in duplicated documentation for the contained fields (e.g. for the example above you get two "Instance fields" headers each containing the same duplicate documentation for foo. Some investigation reveals that it's having the same deduced section name ("Instance fields" in this case) which caused the issue, and that renaming it for one of the files avoid the issue.

This is for master.

**Comment by alerque** [comment]
@artembo Please do open a PR if you have something to contribute towards this, perhaps with some example code it would be more clear what the use case is.
